[package]
name = "a2a-client"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.0" }
a2a-rs = { path = "../a2a-rs", features = ["ws-client"], default-features = false }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
gloo-net = "0.5.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "WebSocket",
    "MessageEvent",
    "BinaryType",
    "CloseEvent",
    "ErrorEvent",
    "console",
    "HtmlInputElement",
    "Event"
]}
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "js"] }
log = "0.4"
console_log = "1.0"
console_error_panic_hook = "0.1"

[features]
default = ["csr"]
csr = []

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]
