[package]
name = "a2a-client"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "cors"] }

# Templates
askama = "0.12"
askama_axum = "0.4"

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# A2A integration
a2a-rs = { path = "../a2a-rs", features = ["http-client", "server"], default-features = false }

# Time handling
chrono = "0.4"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }

[[bin]]
name = "server"
path = "src/bin/server.rs"